# Generated by Django 5.0.1 on 2024-01-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=200)),
                ('fila', models.CharField(max_length=200)),
                ('entrada', models.CharField(max_length=200)),
                ('saida', models.CharField(max_length=200)),
            ],
        ),
    ]
